#!/usr/bin/env bash
# setup.sh - Downloads KKBox data, loads into PostgreSQL, generates enrichment data
# Prerequisites: kaggle CLI, psql, python3
set -euo pipefail

DB_NAME="${PGDATABASE:-subscription_financial_model}"
DB_USER="${PGUSER:-postgres}"
DB_HOST="${PGHOST:-localhost}"
DB_PORT="${PGPORT:-5432}"
DATA_DIR="$(cd "$(dirname "$0")" && pwd)/data/raw"

echo "=== Subscription Financial Model Setup ==="

# --- Step 1: Download KKBox data from Kaggle ---
echo "[1/4] Downloading KKBox dataset from Kaggle..."
mkdir -p "$DATA_DIR"
if [ ! -f "$DATA_DIR/members_v3.csv" ]; then
    kaggle competitions download -c kkbox-churn-prediction-challenge -p "$DATA_DIR"
    cd "$DATA_DIR"
    for f in *.zip; do unzip -o "$f" && rm "$f"; done
    # Handle nested zips
    for f in *.csv.7z; do 7z x "$f" && rm "$f" 2>/dev/null || true; done
    cd -
    echo "    Downloaded and extracted KKBox data"
else
    echo "    KKBox data already exists, skipping download"
fi

# --- Step 2: Create PostgreSQL database and tables ---
echo "[2/4] Creating PostgreSQL database and schema..."
psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -tc \
    "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'" | grep -q 1 || \
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -c "CREATE DATABASE $DB_NAME;"

psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" <<'SQL'
DROP SCHEMA IF EXISTS raw CASCADE;
CREATE SCHEMA raw;

CREATE TABLE raw.members (
    msno              VARCHAR(64) PRIMARY KEY,
    city              INTEGER,
    bd                INTEGER,           -- age (birth date derived)
    gender            VARCHAR(10),
    registered_via    INTEGER,
    registration_init_time VARCHAR(20)   -- YYYYMMDD format
);

CREATE TABLE raw.transactions (
    msno                    VARCHAR(64),
    payment_method_id       INTEGER,
    payment_plan_days       INTEGER,
    plan_list_price         INTEGER,
    actual_amount_paid      INTEGER,
    is_auto_renew           SMALLINT,
    transaction_date        VARCHAR(20),  -- YYYYMMDD
    membership_expire_date  VARCHAR(20),  -- YYYYMMDD
    is_cancel               SMALLINT
);

CREATE TABLE raw.user_logs (
    msno            VARCHAR(64),
    date            VARCHAR(20),         -- YYYYMMDD
    num_25          INTEGER,             -- songs played < 25% duration
    num_50          INTEGER,             -- songs played 25-50%
    num_75          INTEGER,             -- songs played 50-75%
    num_985         INTEGER,             -- songs played 75-98.5%
    num_100         INTEGER,             -- songs played > 98.5%
    num_unq         INTEGER,             -- unique songs
    total_secs      DOUBLE PRECISION     -- total seconds played
);

CREATE TABLE raw.train (
    msno        VARCHAR(64),
    is_churn    SMALLINT
);

-- Enrichment table (generated by Python)
CREATE TABLE raw.marketing_spend (
    month       VARCHAR(7),              -- YYYY-MM
    channel     VARCHAR(30),
    spend       NUMERIC(12,2),
    new_members INTEGER
);

CREATE INDEX idx_transactions_msno ON raw.transactions(msno);
CREATE INDEX idx_user_logs_msno ON raw.user_logs(msno);
CREATE INDEX idx_transactions_date ON raw.transactions(transaction_date);
SQL
echo "    Schema created"

# --- Step 3: Load CSV data ---
echo "[3/4] Loading CSVs into PostgreSQL..."
load_csv() {
    local table=$1
    local file=$2
    if [ -f "$file" ]; then
        psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c \
            "\\copy raw.$table FROM '$file' WITH (FORMAT csv, HEADER true, NULL '')"
        echo "    Loaded $table"
    else
        echo "    WARNING: $file not found, skipping"
    fi
}

load_csv "members"      "$DATA_DIR/members_v3.csv"
load_csv "transactions"  "$DATA_DIR/transactions_v2.csv"
load_csv "user_logs"     "$DATA_DIR/user_logs_v2.csv"
load_csv "train"         "$DATA_DIR/train_v2.csv"

# --- Step 4: Generate synthetic marketing enrichment ---
echo "[4/4] Generating marketing spend enrichment..."
python3 data/generate_enrichment.py

echo ""
echo "=== Setup complete ==="
echo "Database: $DB_NAME"
echo "Run 'dbt build' to create analytics models"
echo "Run 'streamlit run dashboard/app.py' for the interactive dashboard"
